apiVersion: v1
kind: Service
metadata:
  name: python-rest-flask-api-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 9001
    protocol: TCP
  selector:
    app: python-rest-flask-api
